USE DIAMONDPROJECT;
GO

DELETE FROM PENDANT;
DELETE FROM RINGSHAPEDETAIL;
DELETE FROM RING;
DELETE FROM DIAMOND;
DELETE FROM SHAPE;
DELETE FROM SPECIALFEATURE;
DELETE FROM STONECUT;
DELETE FROM METALTYPE;
DELETE FROM FRAMETYPE;
DELETE FROM RINGSUBTYPE;
DELETE FROM RINGTYPE;


INSERT INTO RINGTYPE (RingTypeID, TypeName)
VALUES
    (NEWID(), 'Solitaire'),
    (NEWID(), 'Halo'),
    (NEWID(), 'Sapphire sidestone'),
    (NEWID(), 'Three-stone');

-- Insert data into RINGSUBTYPE table
INSERT INTO RINGSUBTYPE (RingSubtypeID, RingTypeID, SubtypeName)
VALUES
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire'), 'Petite'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire'), 'Classic'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire'), 'Petite Nouveau'),
	(NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire'), 'Riviera'),
	(NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire'), 'Classic Simple'),
	(NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire'), 'Petite Hidden Halo'),
	(NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire'), 'Petite Cathedral'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo'), 'Twisted'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo'), 'Twisted Band'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo'), 'Classic'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone'), 'Classic'),
	(NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone'), 'Riviera'),
	(NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone'), 'Riviera Micropavé'),
	(NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone'), 'Three Row'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Three-stone'), 'Trapezoid'),
	(NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Three-stone'), 'Tapered Baguette');

-- Insert data into FRAMETYPE table
INSERT INTO FRAMETYPE (FrameTypeID, FrameTypeName)
VALUES
    (NEWID(), 'Solitaire'),
	(NEWID(), 'Six-Prong'),
	(NEWID(), 'Four-Prong'),
	(NEWID(), 'Pavé'),
    (NEWID(), 'Halo'),
	(NEWID(), 'Sidestone'),
    (NEWID(), 'Three-stone');

-- Insert data into METALTYPE table
INSERT INTO METALTYPE (MetalTypeID, MetalTypeName)
VALUES
    (NEWID(), '14k White Gold'),
    (NEWID(), '18k White Gold'),
    (NEWID(), 'Platinum'),
    (NEWID(), '18k Yellow Gold'),
    (NEWID(), '18k Rose Gold');

-- Insert data into STONECUT table
INSERT INTO STONECUT (StoneCutID, StoneCutName)
VALUES
    (NEWID(), 'Oval Cut'),
    (NEWID(), 'Cushion Cut'),
    (NEWID(), 'Pear Shaped'),
    (NEWID(), 'Asscher Cut'),
    (NEWID(), 'Princess Cut'),
    (NEWID(), 'Emerald Cut'),
    (NEWID(), 'Tapered Baguette');

-- Insert data into SPECIALFEATURE table
INSERT INTO SPECIALFEATURE (SpecialFeatureID, FeatureDescription)
VALUES
    (NEWID(), 'Halo'),
    (NEWID(), 'Cathedral'),
    (NEWID(), 'Sapphire Profile'),
    (NEWID(), 'Two Stone'),
    (NEWID(), 'Bella Vaughan');

INSERT INTO SHAPE (ShapeID, ShapeName)
VALUES
    (NEWID(), 'Round'),
    (NEWID(), 'Princess'),
    (NEWID(), 'Cushion'),
    (NEWID(), 'Oval'),
    (NEWID(), 'Emerald'),
    (NEWID(), 'Pear'),
    (NEWID(), 'Asscher'),
    (NEWID(), 'Heart'),
    (NEWID(), 'Radiant'),
    (NEWID(), 'Marquise');

INSERT INTO DIAMOND (ImageURL, ShapeID, CaratWeight, Color, Clarity, Cut)
VALUES
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 0.95, 6, 2, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 1.25, 5, 6, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 1.30, 7, 7, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 1.40, 8, 8, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 1.15, 3, 3, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 1.00, 2, 2, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 1.05, 1, 1, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 1.10, 7, 5, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 0.90, 4, 4, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 0.85, 6, 2, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 0.75, 5, 6, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 1.05, 3, 7, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 1.20, 7, 4, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 0.95, 8, 3, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 0.85, 2, 2, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 1.00, 1, 8, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 1.20, 8, 6, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 2.75, 4, 5, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 3.10, 3, 8, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 1.80, 5, 6, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 2.00, 6, 5, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 3.50, 7, 3, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 1.70, 2, 7, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 1.90, 1, 4, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 2.20, 8, 2, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 1.60, 4, 5, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 2.10, 7, 8, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 1.80, 6, 4, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 2.50, 5, 3, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 3.30, 4, 6, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 2.70, 7, 2, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 2.40, 3, 8, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 3.20, 8, 7, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 1.50, 6, 4, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 1.85, 7, 3, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 1.95, 5, 6, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 2.35, 8, 5, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 2.65, 2, 4, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 2.80, 4, 7, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 1.70, 3, 8, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 2.50, 6, 3, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 1.90, 5, 2, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 1.55, 1, 6, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 2.10, 3, 5, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 2.00, 8, 4, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 2.45, 7, 2, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 1.75, 6, 8, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 2.15, 5, 7, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 2.85, 4, 3, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 1.65, 7, 6, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 2.90, 2, 5, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 3.20, 8, 2, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 1.40, 6, 4, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 2.30, 5, 8, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 1.75, 4, 3, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 1.85, 7, 6, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 2.60, 3, 7, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 1.25, 8, 5, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 2.40, 2, 6, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 1.80, 6, 2, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 2.70, 7, 3, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 1.65, 5, 8, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 2.50, 4, 6, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 2.00, 3, 7, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 2.85, 8, 2, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 1.70, 6, 5, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 2.55, 2, 8, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 1.60, 7, 4, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 2.20, 5, 3, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 1.90, 4, 6, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 2.25, 3, 7, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 1.50, 8, 2, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 2.75, 6, 4, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 2.40, 7, 5, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 1.85, 2, 8, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 2.65, 4, 6, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 1.70, 5, 3, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 2.35, 8, 7, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 1.75, 6, 4, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 2.50, 3, 2, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 1.60, 5, 7, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 2.85, 7, 3, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 1.90, 2, 8, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 2.25, 8, 5, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 1.60, 4, 6, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 2.45, 3, 7, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 1.70, 6, 2, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 2.30, 5, 4, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 1.85, 7, 3, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 2.65, 8, 6, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 1.50, 2, 3, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 2.35, 6, 4, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 1.65, 7, 2, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 2.10, 3, 6, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 1.55, 4, 5, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 1.95, 5, 3, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 2.20, 7, 4, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 1.75, 8, 7, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 1.85, 6, 2, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 2.00, 5, 5, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 0.50, 2, 3, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 1.35, 4, 5, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 2.25, 5, 6, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 1.75, 6, 7, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 1.85, 7, 4, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 1.25, 8, 2, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 2.30, 3, 3, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 1.10, 2, 4, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 2.50, 1, 5, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 1.05, 4, 6, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 1.55, 5, 7, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 2.20, 3, 2, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 1.30, 2, 3, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 2.75, 4, 4, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 1.10, 5, 6, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 2.15, 6, 7, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 1.50, 7, 2, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 2.05, 8, 5, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 1.45, 3, 3, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 2.10, 2, 4, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 2.30, 4, 6, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 1.25, 6, 7, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 2.50, 3, 2, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 1.75, 5, 3, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 2.10, 7, 4, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 1.35, 2, 6, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 1.90, 4, 7, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 2.25, 6, 2, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 1.80, 8, 3, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 1.55, 3, 5, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 2.05, 1, 4, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 1.75, 5, 6, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 2.30, 6, 7, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 1.20, 3, 2, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 2.50, 7, 3, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 1.65, 4, 4, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 2.00, 2, 5, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 1.50, 8, 6, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 2.15, 3, 7, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 1.95, 5, 2, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 2.45, 6, 3, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 1.30, 4, 4, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 2.00, 2, 6, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 1.40, 8, 7, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 1.85, 7, 2, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 2.20, 1, 5, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 1.55, 3, 6, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 2.35, 5, 3, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 1.70, 6, 4, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 1.00, 2, 2, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 2.50, 6, 5, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 3.10, 3, 7, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 2.75, 5, 6, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 1.50, 7, 4, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 2.20, 8, 2, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 1.35, 2, 3, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 2.00, 4, 5, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 1.25, 3, 6, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 2.40, 6, 7, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 1.85, 5, 2, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 3.00, 4, 3, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 2.50, 7, 5, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 2.10, 2, 6, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 1.65, 3, 7, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 2.00, 8, 4, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 2.75, 5, 5, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 3.30, 6, 2, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 1.45, 3, 3, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 2.25, 7, 6, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 2.50, 2, 4, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 1.75, 5, 7, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 3.00, 4, 5, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 1.20, 3, 2, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 2.90, 6, 3, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 1.35, 7, 4, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 2.40, 8, 5, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 1.10, 2, 7, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 2.65, 5, 2, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 3.20, 3, 6, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 1.75, 4, 3, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 2.50, 6, 7, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 2.20, 7, 4, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 3.30, 2, 5, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 1.40, 5, 3, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 2.10, 4, 6, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 2.80, 3, 7, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 1.85, 8, 2, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 3.50, 5, 5, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 2.30, 2, 3, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 1.20, 6, 4, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'), 2.65, 7, 6, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'), 3.15, 3, 2, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'), 2.00, 5, 3, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'), 1.85, 2, 7, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'), 2.45, 4, 5, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'), 3.10, 6, 3, 3),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'), 2.70, 7, 4, 2),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'), 1.25, 8, 2, 4),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'), 2.75, 3, 6, 1),
('', (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'), 1.80, 4, 5, 3);

INSERT INTO RING (RingID, RingTypeID, RingSubtypeID, FrameTypeID, MetalTypeID, StoneCutID, SpecialFeatureID, RingName, Price, StockQuantity, ImageURL)
VALUES
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Petite' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Solitaire'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), NULL, NULL, 'Petite Solitaire Engagement Ring in 14k White Gold', 1000.00, 10, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Classic' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Six-Prong'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), NULL, NULL, 'Classic Six-Prong Solitaire Engagement Ring in 14k White Gold', 1200.00, 15, 'image_url_here'),
	(NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Classic' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Four-Prong'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), NULL, NULL, 'Classic Four-Prong Solitaire Engagement Ring in 14k White Gold', 1100.00, 20, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Petite Nouveau' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Six-Prong'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), NULL, NULL, 'Petite Nouveau Six-Prong Solitaire Engagement Ring in 14k White Gold', 1050.00, 12, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Riviera' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Pavé'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), NULL, NULL, 'Riviera Pavé Diamond Engagement Ring in 14k White Gold', 1500.00, 18, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Classic Simple' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Solitaire'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), NULL, NULL, 'Classic Simple Solitaire Engagement Ring in 14k White Gold', 950.00, 25, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Petite Hidden Halo' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Solitaire'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), NULL, (SELECT SpecialFeatureID FROM SPECIALFEATURE WHERE FeatureDescription = 'Halo'), 'Petite Hidden Halo Solitaire Plus Diamond Engagement Ring in 14k White Gold', 1800.00, 15, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Petite Cathedral' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Solitaire')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Solitaire'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), NULL, (SELECT SpecialFeatureID FROM SPECIALFEATURE WHERE FeatureDescription = 'Cathedral'), 'Petite Cathedral Solitaire Engagement Ring in 14k White Gold', 1700.00, 20, 'image_url_here'),

	(NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Twisted' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Halo'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), NULL, NULL, 'Twisted Halo Diamond Engagement Ring in 14k White Gold', 2200.00, 15, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Twisted Band' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Halo'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), NULL, NULL, 'Twisted Band Halo Diamond Engagement Ring in 14k White Gold', 2300.00, 18, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Classic' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Halo'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), (SELECT StoneCutID FROM STONECUT WHERE StoneCutName = 'Oval Cut'), NULL, 'Oval Cut Classic Halo Diamond Engagement Ring in 14k White Gold', 2500.00, 20, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Classic' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Halo'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), NULL, NULL, 'Classic Halo Diamond Engagement Ring in 14k White Gold', 2000.00, 22, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Classic' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Halo'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), (SELECT StoneCutID FROM STONECUT WHERE StoneCutName = 'Cushion Cut'), NULL, 'Cushion Cut Classic Halo Diamond Engagement Ring in 14k White Gold', 2700.00, 25, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Classic' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Halo'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), (SELECT StoneCutID FROM STONECUT WHERE StoneCutName = 'Pear Shaped'), NULL, 'Pear Shaped Classic Halo Diamond Engagement Ring in 14k White Gold', 2600.00, 30, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo'), NULL, (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Halo'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), (SELECT StoneCutID FROM STONECUT WHERE StoneCutName = 'Cushion Cut'), NULL, 'Cushion Halo Diamond Engagement Ring in 14k White Gold', 2400.00, 28, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Classic' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Halo')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Halo'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), (SELECT StoneCutID FROM STONECUT WHERE StoneCutName = 'Asscher Cut'), NULL, 'Asscher Cut Classic Halo Diamond Engagement Ring in 14k White Gold', 2800.00, 24, 'image_url_here'),

	(NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Classic' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone')), NULL, (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '18k White Gold'), (SELECT StoneCutID FROM STONECUT WHERE StoneCutName = 'Pear Shaped'), NULL, 'Classic Pear Shaped Sapphire Engagement Ring in 18k White Gold', 3200.00, 10, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Classic' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone')), NULL, (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = 'Platinum'), (SELECT StoneCutID FROM STONECUT WHERE StoneCutName = 'Pear Shaped'), NULL, 'Classic Pear Shaped Sapphire Engagement Ring in Platinum', 3500.00, 12, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Riviera' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Pavé'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = 'Platinum'), NULL, NULL, 'Riviera Pavé Sapphire and Diamond Engagement Ring in Platinum', 3800.00, 15, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Riviera Micropavé' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Pavé'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), NULL, NULL, 'Riviera Micropavé Sapphire and Diamond Engagement Ring in 14k White Gold', 3400.00, 18, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Riviera Micropavé' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Pavé'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = 'Platinum'), NULL, NULL, 'Riviera Micropavé Sapphire and Diamond Engagement Ring in Platinum', 3700.00, 20, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Three Row' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone')), NULL, (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), NULL, NULL, 'Three Row Sapphire and Diamond Engagement Ring in 14k White Gold', 3300.00, 16, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone'), NULL, (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Halo'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), (SELECT StoneCutID FROM STONECUT WHERE StoneCutName = 'Oval Cut'), NULL, 'Sapphire Profile and Diamond Halo Engagement Ring in 14k White Gold', 3600.00, 14, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Sapphire sidestone'), NULL, NULL, (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), (SELECT StoneCutID FROM STONECUT WHERE StoneCutName = 'Oval Cut'), NULL, 'Two Stone Engagement Ring with Oval Sapphire in 14k White Gold', 3900.00, 17, 'image_url_here'),

	(NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Three-stone'), NULL, (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Sidestone'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), (SELECT StoneCutID FROM STONECUT WHERE StoneCutName = 'Pear Shaped'), NULL, 'Pear Sidestone Diamond Engagement Ring in 14k White Gold', 2800.00, 10, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Three-stone'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Tapered Baguette' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Three-stone')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Sidestone'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), NULL, NULL, 'Tapered Baguette Diamond Engagement Ring in 14k White Gold', 3000.00, 12, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Three-stone'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Tapered Baguette' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Three-stone')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Sidestone'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '14k White Gold'), NULL, NULL, 'Tapered Baguette Diamond Engagement Ring in 14k White Gold (1/6 Ct. Tw.)', 3000.00, 12, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Three-stone'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Trapezoid' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Three-stone')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Three-Stone'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '18k Yellow Gold'), NULL, NULL, 'Bella Vaughan Trapezoid Three Stone Engagement Ring in 18k Yellow Gold', 3200.00, 15, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Three-stone'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Trapezoid' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Three-stone')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Three-Stone'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '18k Rose Gold'), NULL, NULL, 'Three-Stone Trapezoid Sidestone Diamond Engagement Ring in 18k Rose Gold', 3400.00, 18, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Three-stone'), NULL, (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Three-Stone'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '18k Yellow Gold'), (SELECT StoneCutID FROM STONECUT WHERE StoneCutName = 'Princess Cut'), NULL, 'Three-Stone Princess Diamond Engagement Ring in 18k Yellow Gold', 3100.00, 14, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Three-stone'), NULL, (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Three-Stone'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '18k Yellow Gold'), (SELECT StoneCutID FROM STONECUT WHERE StoneCutName = 'Emerald Cut'), NULL, 'Three-Stone Emerald Cut Diamond Engagement Ring in 18k Yellow Gold', 3300.00, 16, 'image_url_here'),
    (NEWID(), (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Three-stone'), (SELECT RingSubtypeID FROM RINGSUBTYPE WHERE SubtypeName = 'Tapered Baguette' AND RingTypeID = (SELECT RingTypeID FROM RINGTYPE WHERE TypeName = 'Three-stone')), (SELECT FrameTypeID FROM FRAMETYPE WHERE FrameTypeName = 'Three-Stone'), (SELECT MetalTypeID FROM METALTYPE WHERE MetalTypeName = '18k Yellow Gold'), NULL, NULL, 'Three-Stone Tapered Baguette Diamond Engagement Ring in 18k Yellow Gold', 3100.00, 13, 'image_url_here');


INSERT INTO RINGSHAPEDETAIL (RingID, ShapeID, ImageURL, FrameDescription) VALUES
-- Insert into RINGSHAPEDETAIL table for solitaire rings
-- 1. Petite Solitaire Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Petite Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'),
 'imageURL_Heart.jpg', 'Suitable for heart diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear diamond'),

-- 2. Classic Six-Prong Solitaire Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Classic Six-Prong Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Six-Prong Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Six-Prong Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear diamond'),

-- 3. Classic Four-Prong Solitaire Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Classic Four-Prong Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Four-Prong Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Four-Prong Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Four-Prong Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Four-Prong Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Four-Prong Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Four-Prong Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher diamond'),

-- 4. Petite Nouveau Six-Prong Solitaire Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Petite Nouveau Six-Prong Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),

-- 5. Riviera Pavé Diamond Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess diamond'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion diamond'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald diamond'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval diamond'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant diamond'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher diamond'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise diamond'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'),
 'imageURL_Heart.jpg', 'Suitable for heart diamond'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear diamond'),

-- 6. Classic Simple Solitaire Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Classic Simple Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Simple Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Simple Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Simple Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Simple Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Simple Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Simple Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Simple Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Simple Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'),
 'imageURL_Heart.jpg', 'Suitable for heart diamond'),
((SELECT RingID FROM RING WHERE RingName='Classic Simple Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear diamond'),

-- 7. Petite Hidden Halo Solitaire Plus Diamond Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Petite Hidden Halo Solitaire Plus Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Hidden Halo Solitaire Plus Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Hidden Halo Solitaire Plus Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Hidden Halo Solitaire Plus Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Hidden Halo Solitaire Plus Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Hidden Halo Solitaire Plus Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Hidden Halo Solitaire Plus Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Hidden Halo Solitaire Plus Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'),
 'imageURL_Heart.jpg', 'Suitable for heart diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Hidden Halo Solitaire Plus Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear diamond'),

-- 8. Petite Cathedral Solitaire Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Petite Cathedral Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Cathedral Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Cathedral Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Cathedral Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Cathedral Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Cathedral Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Cathedral Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Cathedral Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Cathedral Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'),
 'imageURL_Heart.jpg', 'Suitable for heart diamond'),
((SELECT RingID FROM RING WHERE RingName='Petite Cathedral Solitaire Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear diamond'),

-- Insert into RINGSHAPEDETAIL table for halo rings
-- 1. Twisted Halo Diamond Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Twisted Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),

-- 2. Twisted Band Halo Diamond Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Twisted Band Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),
((SELECT RingID FROM RING WHERE RingName='Twisted Band Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess diamond'),
((SELECT RingID FROM RING WHERE RingName='Twisted Band Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion diamond'),
((SELECT RingID FROM RING WHERE RingName='Twisted Band Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald diamond'),
((SELECT RingID FROM RING WHERE RingName='Twisted Band Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval diamond'),
((SELECT RingID FROM RING WHERE RingName='Twisted Band Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant diamond'),
((SELECT RingID FROM RING WHERE RingName='Twisted Band Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher diamond'),
((SELECT RingID FROM RING WHERE RingName='Twisted Band Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise diamond'),
((SELECT RingID FROM RING WHERE RingName='Twisted Band Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'),
 'imageURL_Heart.jpg', 'Suitable for heart diamond'),
((SELECT RingID FROM RING WHERE RingName='Twisted Band Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear diamond'),

-- 3. Oval Cut Classic Halo Diamond Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Oval Cut Classic Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval diamond'),

-- 4. Classic Halo Diamond Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Classic Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),

-- 5. Cushion Cut Classic Halo Diamond Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Cushion Cut Classic Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion diamond'),

-- 6. Pear Shaped Classic Halo Diamond Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Pear Shaped Classic Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear diamond'),

-- 7. Cushion Halo Diamond Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Cushion Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion diamond'),

-- 8. Asscher Cut Classic Halo Diamond Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Asscher Cut Classic Halo Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher diamond'),

 -- Insert into RINGSHAPEDETAIL table for Sapphire sidestone rings
-- 1. Classic Pear Shaped Sapphire Engagement Ring in 18k White Gold
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in 18k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round sapphire'),
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in 18k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess sapphire'),
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in 18k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion sapphire'),
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in 18k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald sapphire'),
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in 18k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval sapphire'),
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in 18k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant sapphire'),
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in 18k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher sapphire'),
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in 18k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise sapphire'),

-- 2. Classic Pear Shaped Sapphire Engagement Ring in Platinum
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round sapphire'),
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess sapphire'),
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion sapphire'),
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald sapphire'),
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval sapphire'),
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant sapphire'),
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher sapphire'),
((SELECT RingID FROM RING WHERE RingName='Classic Pear Shaped Sapphire Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise sapphire'),

-- 3. Riviera Pavé Sapphire and Diamond Engagement Ring in Platinum
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'),
 'imageURL_Heart.jpg', 'Suitable for heart-shaped sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Pavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear-shaped sapphire'),

-- 4. Riviera Micropavé Sapphire and Diamond Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'),
 'imageURL_Heart.jpg', 'Suitable for heart-shaped sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear-shaped sapphire'),

-- 5. Riviera Micropavé Sapphire and Diamond Engagement Ring in Platinum
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'),
 'imageURL_Heart.jpg', 'Suitable for heart-shaped sapphire'),
((SELECT RingID FROM RING WHERE RingName='Riviera Micropavé Sapphire and Diamond Engagement Ring in Platinum'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear-shaped sapphire'),

-- 6. Three Row Sapphire and Diamond Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Three Row Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round sapphire'),
((SELECT RingID FROM RING WHERE RingName='Three Row Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess sapphire'),
((SELECT RingID FROM RING WHERE RingName='Three Row Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion sapphire'),
((SELECT RingID FROM RING WHERE RingName='Three Row Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald sapphire'),
((SELECT RingID FROM RING WHERE RingName='Three Row Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval sapphire'),
((SELECT RingID FROM RING WHERE RingName='Three Row Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant sapphire'),
((SELECT RingID FROM RING WHERE RingName='Three Row Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher sapphire'),
((SELECT RingID FROM RING WHERE RingName='Three Row Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise sapphire'),
((SELECT RingID FROM RING WHERE RingName='Three Row Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'),
 'imageURL_Heart.jpg', 'Suitable for heart-shaped sapphire'),
((SELECT RingID FROM RING WHERE RingName='Three Row Sapphire and Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear-shaped sapphire'),

-- 7. Sapphire Profile and Diamond Halo Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Sapphire Profile and Diamond Halo Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round sapphire'),

-- 8. Two Stone Engagement Ring with Oval Sapphire in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Two Stone Engagement Ring with Oval Sapphire in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval sapphire'),

-- Insert into RINGSHAPEDETAIL table for three-stone rings
-- 1. Pear Sidestone Diamond Engagement Ring in 14k White Gold
((SELECT RingID FROM RING WHERE RingName='Pear Sidestone Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),
((SELECT RingID FROM RING WHERE RingName='Pear Sidestone Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess diamond'),
((SELECT RingID FROM RING WHERE RingName='Pear Sidestone Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion diamond'),
((SELECT RingID FROM RING WHERE RingName='Pear Sidestone Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald diamond'),
((SELECT RingID FROM RING WHERE RingName='Pear Sidestone Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval diamond'),
((SELECT RingID FROM RING WHERE RingName='Pear Sidestone Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant diamond'),
((SELECT RingID FROM RING WHERE RingName='Pear Sidestone Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise diamond'),
((SELECT RingID FROM RING WHERE RingName='Pear Sidestone Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'),
 'imageURL_Heart.jpg', 'Suitable for heart diamond'),
((SELECT RingID FROM RING WHERE RingName='Pear Sidestone Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear diamond'),

-- 2. Tapered Baguette Diamond Engagement Ring in 14k White Gold (first entry)
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'),
 'imageURL_Heart.jpg', 'Suitable for heart diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear diamond'),

-- 3. Tapered Baguette Diamond Engagement Ring in 14k White Gold (second entry)
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold (1/6 Ct. Tw.)'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold (1/6 Ct. Tw.)'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold (1/6 Ct. Tw.)'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold (1/6 Ct. Tw.)'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold (1/6 Ct. Tw.)'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold (1/6 Ct. Tw.)'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold (1/6 Ct. Tw.)'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold (1/6 Ct. Tw.)'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Heart'),
 'imageURL_Heart.jpg', 'Suitable for heart diamond'),
((SELECT RingID FROM RING WHERE RingName='Tapered Baguette Diamond Engagement Ring in 14k White Gold (1/6 Ct. Tw.)'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear diamond'),

-- 4. Bella Vaughan Trapezoid Three Stone Engagement Ring in 18k Yellow Gold
((SELECT RingID FROM RING WHERE RingName='Bella Vaughan Trapezoid Three Stone Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),
((SELECT RingID FROM RING WHERE RingName='Bella Vaughan Trapezoid Three Stone Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess diamond'),
((SELECT RingID FROM RING WHERE RingName='Bella Vaughan Trapezoid Three Stone Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald diamond'),
((SELECT RingID FROM RING WHERE RingName='Bella Vaughan Trapezoid Three Stone Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant diamond'),

-- 5. Three-Stone Trapezoid Sidestone Diamond Engagement Ring in 18k Rose Gold
((SELECT RingID FROM RING WHERE RingName='Three-Stone Trapezoid Sidestone Diamond Engagement Ring in 18k Rose Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald diamond'),
((SELECT RingID FROM RING WHERE RingName='Three-Stone Trapezoid Sidestone Diamond Engagement Ring in 18k Rose Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher diamond'),

-- 6. Three-Stone Princess Diamond Engagement Ring in 18k Yellow Gold
((SELECT RingID FROM RING WHERE RingName='Three-Stone Princess Diamond Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),
((SELECT RingID FROM RING WHERE RingName='Three-Stone Princess Diamond Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Princess'),
 'imageURL_Princess.jpg', 'Suitable for princess diamond'),
((SELECT RingID FROM RING WHERE RingName='Three-Stone Princess Diamond Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion diamond'),
((SELECT RingID FROM RING WHERE RingName='Three-Stone Princess Diamond Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant diamond'),

-- 7. Three-Stone Emerald Cut Diamond Engagement Ring in 18k Yellow Gold
((SELECT RingID FROM RING WHERE RingName='Three-Stone Emerald Cut Diamond Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),
((SELECT RingID FROM RING WHERE RingName='Three-Stone Emerald Cut Diamond Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald diamond'),
((SELECT RingID FROM RING WHERE RingName='Three-Stone Emerald Cut Diamond Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher diamond'),

-- 8. Three-Stone Tapered Baguette Diamond Engagement Ring in 18k Yellow Gold
((SELECT RingID FROM RING WHERE RingName='Three-Stone Tapered Baguette Diamond Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Round'),
 'imageURL_Round.jpg', 'Suitable for round diamond'),
((SELECT RingID FROM RING WHERE RingName='Three-Stone Tapered Baguette Diamond Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Cushion'),
 'imageURL_Cushion.jpg', 'Suitable for cushion diamond'),
((SELECT RingID FROM RING WHERE RingName='Three-Stone Tapered Baguette Diamond Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Emerald'),
 'imageURL_Emerald.jpg', 'Suitable for emerald diamond'),
((SELECT RingID FROM RING WHERE RingName='Three-Stone Tapered Baguette Diamond Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Oval'),
 'imageURL_Oval.jpg', 'Suitable for oval diamond'),
((SELECT RingID FROM RING WHERE RingName='Three-Stone Tapered Baguette Diamond Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Radiant'),
 'imageURL_Radiant.jpg', 'Suitable for radiant diamond'),
((SELECT RingID FROM RING WHERE RingName='Three-Stone Tapered Baguette Diamond Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Asscher'),
 'imageURL_Asscher.jpg', 'Suitable for asscher diamond'),
((SELECT RingID FROM RING WHERE RingName='Three-Stone Tapered Baguette Diamond Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Marquise'),
 'imageURL_Marquise.jpg', 'Suitable for marquise diamond'),
((SELECT RingID FROM RING WHERE RingName='Three-Stone Tapered Baguette Diamond Engagement Ring in 18k Yellow Gold'),
 (SELECT ShapeID FROM SHAPE WHERE ShapeName='Pear'),
 'imageURL_Pear.jpg', 'Suitable for pear diamond');

 INSERT INTO PENDANT (Name, Price, StockQuantity, ChainType, ChainLength, ClaspType)
 VALUES
    ('Elegant Pearl Pendant', 150, 25, 'Cable Chain', '16-18 inches', 'Lobster Claw Clasp'),
    ('Sparkling Diamond Pendant', 251, 30, 'Box Chain', '18 inches', 'Spring Ring Clasp'),
    ('Golden Heart Pendant', 200, 10, 'Rope Chain', '20 inches', 'Magnetic Clasp'),
    ('Silver Star Pendant', 121, 50, 'Snake Chain', '22 inches', 'Toggle Clasp'),
    ('Rose Gold Infinity Pendant', 175, 15, 'Figaro Chain', '16 inches', 'Box Clasp'),
    ('Emerald Teardrop Pendant', 220, 20, 'Ball Chain', '18-20 inches', 'Barrel Clasp'),
    ('Blue Sapphire Pendant', 200, 12, 'Singapore Chain', '20 inches', 'S Hook Clasp'),
    ('Ruby Pendant with Diamonds', 321, 5, 'Wheat Chain', '24 inches', 'Fish Hook Clasp'),
    ('Platinum Cross Pendant', 275, 18, 'Cable Chain', '16-18 inches', 'Spring Ring Clasp'),
    ('Amethyst Circle Pendant', 146, 25, 'Rope Chain', '18 inches', 'Magnetic Clasp'),
    ('Pearl Pendant in Gold', 180, 22, 'Snake Chain', '20 inches', 'Lobster Claw Clasp'),
    ('Garnet Heart Pendant', 160, 28, 'Box Chain', '22 inches', 'Toggle Clasp'),
    ('Peridot Drop Pendant', 190, 16, 'Figaro Chain', '16-18 inches', 'Box Clasp'),
    ('Citrine Sun Pendant', 175, 10, 'Ball Chain', '18-20 inches', 'Barrel Clasp'),
    ('Opal Teardrop Pendant', 211, 7, 'Singapore Chain', '20 inches', 'S Hook Clasp'),
    ('Aquamarine Pendant', 195, 30, 'Wheat Chain', '24 inches', 'Fish Hook Clasp'),
    ('Turquoise Oval Pendant', 170, 12, 'Cable Chain', '16-18 inches', 'Spring Ring Clasp'),
    ('Onyx Stone Pendant', 150, 20, 'Rope Chain', '18 inches', 'Magnetic Clasp'),
    ('Moonstone Pendant', 226, 10, 'Snake Chain', '20 inches', 'Lobster Claw Clasp'),
    ('Topaz Pendant with Silver', 205, 18, 'Box Chain', '22 inches', 'Toggle Clasp');