SELECT * FROM [DIAMONDPROJECT].[dbo].[ORDERS]
SELECT * FROM [dbo].[ORDERITEM]
SELECT * FROM VNPaymentRequest
SELECT * FROM VNPaymentResponse

--See if order stuffs still exist
SELECT * FROM [dbo].[RINGPAIRING]
SELECT * FROM [dbo].[PENDANTPAIRING]
SELECT * FROM [dbo].[EARRINGPAIRING]

SELECT * FROM DIAMOND

--Reset orders
DELETE FROM VNPaymentResponse
DELETE FROM VNPaymentRequest
DELETE FROM [dbo].[ORDERITEM]
DELETE FROM [dbo].[ORDERS]
DELETE FROM [dbo].[RINGPAIRING]
DELETE FROM [dbo].[PENDANTPAIRING]
DELETE FROM [dbo].[EARRINGPAIRING]
UPDATE DIAMOND
SET Available = 1;
--Ends here

SELECT * FROM [dbo].[CUSTOMER]
DELETE FROM [dbo].[CUSTOMER]

--Don't touch here oge
SELECT 
    r.RingName, 
    rsd.ImageURL, 
    rsd.FrameDescription 
FROM 
    RING r
--ogey (=w=)=b
-- Haro
JOIN 
    RINGSHAPEDETAIL rsd ON r.RingID = rsd.RingID
JOIN 
    SHAPE s ON rsd.ShapeID = s.ShapeID
WHERE 
    s.ShapeName = 'Round';

-- For testing hangfire
UPDATE Orders
SET OrderDate = DATEADD(DAY, -1, OrderDate)

UPDATE Orders
SET OrderDate = DATEADD(MINUTE, -5, OrderDate)

UPDATE ORDERS
SET OrderEmail = 'khangbinh167@gmail.com'

UPDATE ORDERS
SET OrderStatus = 'Processing'
WHERE OrderID = '64323E44-5839-4055-A26E-8FD059A5E446'

SELECT * FROM [DIAMONDPROJECT].[dbo].[ORDERS]
SELECT * FROM [dbo].[ORDERITEM]

SELECT * FROM RING WHERE RingID = '2A097147-C80E-4D8F-8289-00D6A8A26157'
SELECT * FROM RINGTYPE WHERE RingTypeID = '9C5B5F5D-B782-442F-98FC-E9EF6B1D5D2F'
SELECT * FROM RINGSUBTYPE WHERE RingSubtypeID = ''
SELECT * FROM FRAMETYPE WHERE FrameTypeID = 'D593848E-E179-435B-BFAC-973ED171B42A'
SELECT * FROM STONECUT WHERE StoneCutID = 'B6F293E6-3391-42F5-947B-B97054596C39'
